routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MateriController@user')->name('materi.user');

Auth::routes();

Route::get('/profile', 'UserController@profile')->middleware('auth')->name('profile');
Route::post('/profile', 'UserController@update_photo')->middleware('auth')->name('update_photo');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('materis', 'MaterisController')->middleware('auth');
Route::resource('sub-materi', 'SubMateriController')->middleware('auth');
Route::resource('soal', 'SoalController')->middleware('auth');
Route::resource('materi-images', 'MateriImagesController')->middleware('auth');
Route::resource('sub-materi-images', 'SubMateriImagesController')->middleware('auth');
Route::resource('soal-images', 'SoalImagesController')->middleware('auth');

Route::get('/materi/{id}', 'MateriController@index')->name('materi');
Route::post('/materi/latihan/', 'MateriController@score')->name('materi.score');
Route::get('/materi/latihan/{id}', 'MateriController@soal')->name('materi.latihan');


Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Soal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Soal extends Model
{
    protected $fillable = [
        'pertanyaan', 'a', 'b', 'c', 'd', 'e', 'jawaban_benar'
    ];


    public function materi()
    {
        return $this->belongsTo(Materi::class, 'materi_id', 'id');
    }

    public function soal_images()
    {
        return $this->hasMany(SoalImages::class, 'materi_id');
    }

}

app/Http/Controllers/SoalController.php
<?php

namespace App\Http\Controllers;

use App\Materi;
use App\Soal;
use Illuminate\Http\Request;
use Illuminate\Validation\Validator;

class SoalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $soals = Soal::with('materi')->latest()->paginate(10);

        return view('soal.index', compact('soals'),[
            "title" => "Daftar Soal"
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $materis = Materi::all();

        return view('soal.create', compact('materis'),[
            "title" => "Tambah Soal"
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'materi_id' => 'required',
            'pertanyaan' => 'required',
            'a' => 'required',
            'b' => 'required',
            'c' => 'required',
            'd' => 'required',
            'e' => 'required',
            'jawaban_benar' => 'required'
        ]);


        $soal = new Soal;
        $soal->materi_id = $request->materi_id;
        $soal->pertanyaan = $request->pertanyaan;
        $soal->a = $request->a;
        $soal->b = $request->b;
        $soal->c = $request->c;
        $soal->d = $request->d;
        $soal->e = $request->e;
        $soal->jawaban_benar = $request->jawaban_benar;
        $soal->save();

        return redirect()->route('soal.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Soal $soal)
    {
        $materis = Materi::paginate(10);

        return view('soal.edit', compact('soal', 'materis'),[
            "title" => "Edit Soal"
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'pertanyaan' => 'required',
            'materi_id' => 'required',
            'a' => 'required',
            'b' => 'required',
            'c' => 'required',
            'd' => 'required',
            'e' => 'required',
            'jawaban_benar' => 'required',
        ]);

        $soal = Soal::find($id);
        $soal->pertanyaan = $request->pertanyaan;
        $soal->materi_id = $request->materi_id;
        $soal->a = $request->a;
        $soal->b = $request->b;
        $soal->c = $request->c;
        $soal->d = $request->d;
        $soal->e = $request->e;
        $soal->jawaban_benar = $request->jawaban_benar;
        $soal->save();

        return redirect()->route('soal.index')
                        ->with('success','Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Soal $soal)
    {
        $soal->delete();

        return redirect()->route('soal.index');
    }

    public function getScore($id)
    {

    }
}

resources/views/soal/create.blade.php
@extends('admin.template.default')

@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            <!--begin::Row-->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card card-custom">
                        <div class="card-header">
                        <h3 class="card-title">
                        Soal Inputs
                        </h3>
                        </div>
                        <!--begin::Form-->
                        <form action="{{ route('soal.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                        <div class="card-body">
                            <div class="form-group row">
                                <label  class="col-2 col-form-label">Nama Materi</label>
                                    <div class="col-10">
                                        <select name="materi_id" class="form-control">
                                            @foreach ($materis as $materi)
                                                <option value="{{ $materi->id }}">{{ $materi->title }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                            </div>
                            <div class="form-group row">
                                <label  class="col-2 col-form-label">Pertanyaan</label>
                                <div class="col-10">
                                    <textarea class="form-control" id="ckeditor" name="pertanyaan" type="text" placeholder="Pertanyaan" id="example-text-input"/></textarea>
                                </div>
                            </div>
                        <div class="form-group row">
                        <label for="example-search-input" class="col-2 col-form-label">Jawaban A</label>
                        <div class="col-10">
                            <input class="form-control" name="a" type="search" placeholder="Jawaban A" id="example-search-input"/>
                        </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban B</label>
                            <div class="col-10">
                                <input class="form-control" name="b" type="search" placeholder="Jawaban B" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban C</label>
                            <div class="col-10">
                                <input class="form-control" name="c" type="search" placeholder="Jawaban C" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban D</label>
                            <div class="col-10">
                                <input class="form-control" name="d" type="search" placeholder="Jawaban D" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban E</label>
                            <div class="col-10">
                                <input class="form-control" name="e" type="search" placeholder="Jawaban e" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban Benar <span class="text-danger">*</span></label>
                            <div class="col-10">
                                <select class="form-control" name="jawaban_benar" id="exampleSelect1">
                                    <option value="a">A</option>
                                    <option value="b">B</option>
                                    <option value="c">C</option>
                                    <option value="d">D</option>
                                    <option value="e">E</option>
                                </select>
                            </div>
                        </div>
                        <div class="card-footer">
                        <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-10">
                            <button type="submit" class="btn btn-success mr-2">Submit</button>
                            <a href="{{ route('soal.index') }}" class="btn btn-secondary">Cancel</a>
                        </div>
                        </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/soal/edit.blade.php
@extends('admin.template.default')

@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Dashboard-->
            <!--begin::Row-->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card card-custom">
                        <div class="card-header">
                        <h3 class="card-title">
                        Soal Inputs
                        </h3>
                        </div>
                        <!--begin::Form-->
                        <form action="{{ route('soal.update',$soal->id) }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                        <div class="card-body">
                            <div class="form-group row">
                                <label  class="col-2 col-form-label">Nama Materi</label>
                                    <div class="col-10">
                                        <select name="materi_id" class="form-control">
                                            @foreach ($materis as $materi)
                                                <option value="{{ $materi->id }}">{{ $materi->title }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                            </div>
                        <div class="form-group row">
                        <label  class="col-2 col-form-label">Pertanyaan</label>
                        <div class="col-10">
                            <textarea class="form-control" name="pertanyaan" type="text" placeholder="Pertanyaan" id="ckeditor"/>{{ $soal->pertanyaan }}</textarea>
                        </div>
                        </div>
                        <div class="form-group row">
                        <label for="example-search-input" class="col-2 col-form-label">Jawaban A</label>
                        <div class="col-10">
                            <input class="form-control" name="a" value="{{ $soal->a }}" type="search" placeholder="Jawaban A" id="example-search-input"/>
                        </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban B</label>
                            <div class="col-10">
                                <input class="form-control" name="b" value="{{ $soal->b }}" type="search" placeholder="Jawaban B" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban C</label>
                            <div class="col-10">
                                <input class="form-control" name="c" value="{{ $soal->c }}" type="search" placeholder="Jawaban C" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban D</label>
                            <div class="col-10">
                                <input class="form-control" name="d" value="{{ $soal->d }}" type="search" placeholder="Jawaban D" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Jawaban E</label>
                            <div class="col-10">
                                <input class="form-control" name="e" value="{{ $soal->e }}" type="search" placeholder="Jawaban E" id="example-search-input"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="example-search-input" class="col-2 col-form-label">Ubah Jawaban<span class="text-danger">*</span></label>
                            <div class="col-10">
                                <select class="form-control" name="jawaban_benar" id="exampleSelect1">
                                    <option value="a">A</option>
                                    <option value="b">B</option>
                                    <option value="c">C</option>
                                    <option value="d">D</option>
                                    <option value="e">E</option>
                                </select>
                            </div>
                        </div>
                        {{-- <div class="form-group row">
                            <label  class="col-2 col-form-label">Image Baru</label>
                                <div class="col-10">
                                    <input class="form-control" name="image" type="file" placeholder="Image" id="example-text-input"/>
                                </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-2 col-form-label">Image Lama</label>
                                <div class="col-10">
                                    <img src="{{ Storage::url($soal->image) }}" alt="" width="112px" />
                                </div>
                        </div> --}}
                        <div class="card-footer">
                        <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-10">
                            <button type="submit" class="btn btn-success mr-2">Submit</button>
                            <a href="{{ route('soal.index') }}" class="btn btn-secondary">Cancel</a>
                        </div>
                        </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/soal/index.blade.php
@extends('admin.template.default')

@section('content')
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-6 subheader-transparent" id="kt_subheader">
        <div class="container d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-1">
                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h5 class="text-dark font-weight-bold my-1 mr-5">Local Data</h5>
                    <!--end::Page Title-->
                    <!--begin::Breadcrumb-->
                    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                        <li class="breadcrumb-item text-muted">
                            <a href="#" class="text-muted">Crud</a>
                        </li>
                        <li class="breadcrumb-item text-muted">
                            <a href="#" class="text-muted">Soal</a>
                        </li>
                        <li class="breadcrumb-item text-muted">
                            <a href="#" class="text-muted">List Soal</a>
                        </li>
                    </ul>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::Info-->
            <!--begin::Toolbar-->
            <div class="d-flex align-items-center">
                <!--begin::Actions-->
                <a href="{{ route('soal.create') }}" class="btn btn-light-primary font-weight-bolder btn-sm">Add New</a>
                <!--end::Actions-->
                <!--begin::Dropdown-->
                <!--end::Dropdown-->
            </div>
            <!--end::Toolbar-->
        </div>
    </div>
    <!--end::Subheader-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Notice-->
            <!--end::Notice-->
            <!--begin::Card-->
            <div class="card card-custom">
                <div class="card-header flex-wrap border-0 pt-6 pb-0">
                    <div class="card-title">
                        <h3 class="card-label">List Soal
                        <span class="text-muted pt-2 font-size-sm d-block">Soal yang telah dibuat</span></h3>
                    </div>
                    <div class="card-toolbar">
                        <!--begin::Dropdown-->

                        <!--end::Dropdown-->
                        <!--begin::Button-->

                        <!--end::Button-->
                    </div>
                </div>
                <div class="card-body">
                    <!--begin: Search Form-->
                    <!--begin::Search Form-->
                    <div class="mb-7">
                        <div class="row align-items-center">
                            <div class="col-lg-9 col-xl-8">
                                <div class="row align-items-center">
                                    <div class="col-md-4 my-2 my-md-0">
                                        <div class="input-icon">
                                            <input type="text" class="form-control" placeholder="Search..." id="kt_datatable_search_query" />
                                            <span>
                                                <i class="flaticon2-search-1 text-muted"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-md-4 my-2 my-md-0">
                                        <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Search</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end::Search Form-->
                    <!--end: Search Form-->
                    <!--begin: Datatable-->
                    <div class="datatable datatable-bordered datatable-head-custom datatable-default datatable-primary datatable-loaded"
                    id="kt_datatable" style="position: static; zoom: 1;">
                    <table class="datatable-table" style="display: block;">
                        <thead class="datatable-head">
                            <tr class="datatable-row" style="left: 0px;">
                                <th data-field="OrderID" class="datatable-cell"><span
                                        style="width: 112px;">Soal ID</span></th>
                                <th data-field="OrderID" class="datatable-cell"><span
                                        style="width: 112px;">Nama Materi</span></th>
                                <th data-field="Country" class="datatable-cell"><span
                                        style="width: 112px;">Pertanyaan</span></th>
                                <th data-field="Type" class="datatable-cell">
                                    <span style="width: 112px;">Jawaban</span></th>
                                {{-- <th data-field="Type" class="datatable-cell">
                                    <span style="width: 112px;">Image</span>
                                </th> --}}
                                <th data-field="Actions" class="datatable-cell">
                                    <span style="width: 125px;">Actions</span></th>
                            </tr>
                        </thead>
                        <tbody class="datatable-body" style="">
                            @foreach ($soals as $soal)
                            <tr data-row="0" class="datatable-row" style="left: 0px;">
                                <td class="datatable-cell"><span style="width: 112px;">#{{ $soal->id }}</span></td>
                                <td class="datatable-cell"><span style="width: 112px;">{{ $soal->materi->title }}</span></td>
                                <td class="datatable-cell"><span style="width: 112px;">{{ $soal->pertanyaan }}</span></td>
                                <td data-field="Type" data-autohide-disabled="false" aria-label="2" class="datatable-cell"><span
                                        style="width: 112px;"><span
                                            class="font-weight-bold text-success">{{ $soal->jawaban_benar }}</span></span></td>
                                {{-- <td class="datatable-cell"><img src="{{ Storage::url($soal->image) }}" alt="" width="112px" /></td> --}}
                                <td data-field="Actions" data-autohide-disabled="false" aria-label="null" class="datatable-cell">

                                    <span style="overflow: visible; position: relative; width: 125px;">
                                        <form action="{{ route('soal.destroy',$soal->id) }}" method="POST">
                                        <a href="{{ route('soal.edit',$soal->id) }}" class="btn btn-sm btn-clean btn-icon mr-2" title="Edit details">
                                            <span class="svg-icon svg-icon-md"> <svg
                                                    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                                    width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"></rect>
                                                        <path
                                                            d="M8,17.9148182 L8,5.96685884 C8,5.56391781 8.16211443,5.17792052 8.44982609,4.89581508 L10.965708,2.42895648 C11.5426798,1.86322723 12.4640974,1.85620921 13.0496196,2.41308426 L15.5337377,4.77566479 C15.8314604,5.0588212 16,5.45170806 16,5.86258077 L16,17.9148182 C16,18.7432453 15.3284271,19.4148182 14.5,19.4148182 L9.5,19.4148182 C8.67157288,19.4148182 8,18.7432453 8,17.9148182 Z"
                                                            fill="#000000" fill-rule="nonzero"
                                                            transform="translate(12.000000, 10.707409) rotate(-135.000000) translate(-12.000000, -10.707409) ">
                                                        </path>
                                                        <rect fill="#000000" opacity="0.3" x="5" y="20" width="15" height="2"
                                                            rx="1"></rect>
                                                    </g>
                                                </svg>
                                            </span>
                                        </a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-clean btn-icon" title="Delete">
                                            <span class="svg-icon svg-icon-md"> <svg
                                                    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                                    width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"></rect>
                                                        <path
                                                            d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z"
                                                            fill="#000000" fill-rule="nonzero"></path>
                                                        <path
                                                            d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
                                                            fill="#000000" opacity="0.3"></path>
                                                    </g>
                                                </svg>
                                            </span>
                                        </button>
                                    </form>
                                    </span>

                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="datatable-pager datatable-paging-loaded">
                        <ul class="datatable-pager-nav my-2 mb-sm-0">
                            <li><a title="First"
                                    class="datatable-pager-link datatable-pager-link-first datatable-pager-link-disabled"
                                    data-page="1" disabled="disabled"><i class="flaticon2-fast-back"></i></a></li>
                            <li><a title="Previous"
                                    class="datatable-pager-link datatable-pager-link-prev datatable-pager-link-disabled"
                                    data-page="1" disabled="disabled"><i class="flaticon2-back"></i></a></li>
                            <li style="display: none;"><input type="text" class="datatable-pager-input form-control"
                                    title="Page number"></li>
                            <li><a class="datatable-pager-link datatable-pager-link-number datatable-pager-link-active"
                                    data-page="1" title="1">1</a></li>
                            <li><a class="datatable-pager-link datatable-pager-link-number" data-page="2" title="2">2</a></li>
                            <li><a class="datatable-pager-link datatable-pager-link-number" data-page="3" title="3">3</a></li>
                            <li><a class="datatable-pager-link datatable-pager-link-number" data-page="4" title="4">4</a></li>
                            <li><a class="datatable-pager-link datatable-pager-link-number" data-page="5" title="5">5</a></li>
                            <li><a title="Next" class="datatable-pager-link datatable-pager-link-next" data-page="2"><i
                                        class="flaticon2-next"></i></a></li>
                            <li><a title="Last" class="datatable-pager-link datatable-pager-link-last" data-page="20"><i
                                        class="flaticon2-fast-next"></i></a></li>
                        </ul>
                    </div>
                </div>
                    <!--end: Datatable-->
                </div>
            </div>
            <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
</div>
@endsection